## 题目一：

已知列表x0，x1，x2：

x0是一个包含长度为10、元素值全部为1的一维数组；

    x1 = [64.3, 99.6, 145.45, 63.75, 135.46, 92.85, 86.97, 144.76, 59.3, 116.03]

    x2 =[2, 3, 4, 2, 3, 4, 2, 4, 1, 3]

    y = [62.55, 82.42, 132.62, 73.31, 131.05, 86.57, 85.49, 127.44, 55.25, 104.84]

要求：

(1) 将x0、x1、x2堆叠为一个10×3的二维数组X，其中x0、x1、x2依次是第1列，第2列和第3列；将y变换为10×1的二维数组Y。

(2) 计算：$ W = \left ( X^TX \right )^{-1 }X^TY $ ，并回答：W的属性shape属性结果是什么？

(3) 分别输出X，Y和W。

In [1]:
import numpy as np

# 已知列表 x0，x1，x2
x0 = np.ones(10)
x1 = np.array([64.3, 99.6, 145.45, 63.75, 135.46, 92.85, 86.97, 144.76, 59.3, 116.03])
x2 = np.array([2, 3, 4, 2, 3, 4, 2, 4, 1, 3])
y = np.array([62.55, 82.42, 132.62, 73.31, 131.05, 86.57, 85.49, 127.44, 55.25, 104.84])

# (1) 将x0、x1、x2堆叠为一个10×3的二维数组X，其中x0、x1、x2依次是第1列，第2列和第3列；将y变换为10×1的二维数组Y。
X = np.column_stack((x0, x1, x2))
Y = y.reshape(-1, 1)

# (2) 计算W 
W = np.linalg.inv(X.T @ X) @ X.T @ Y

# (3) 分别输出X，Y和W
print("X:")
print(X)
print("Y:")
print(Y)
print("W:")
print(W)
print("W的shape属性结果是:", W.shape)


X:
[[  1.    64.3    2.  ]
 [  1.    99.6    3.  ]
 [  1.   145.45   4.  ]
 [  1.    63.75   2.  ]
 [  1.   135.46   3.  ]
 [  1.    92.85   4.  ]
 [  1.    86.97   2.  ]
 [  1.   144.76   4.  ]
 [  1.    59.3    1.  ]
 [  1.   116.03   3.  ]]
Y:
[[ 62.55]
 [ 82.42]
 [132.62]
 [ 73.31]
 [131.05]
 [ 86.57]
 [ 85.49]
 [127.44]
 [ 55.25]
 [104.84]]
W:
[[10.72771277]
 [ 0.87654538]
 [-1.7752445 ]]
W的shape属性结果是: (3, 1)


## 题目二：
已知列表x，y，按要求计算：

    x = [64.3, 99.6, 145.45, 63.75, 135.46, 92.85, 86.97, 144.76, 59.3, 116.03]

    y = [62.55, 82.42, 132.62, 73.31, 131.05, 86.57, 85.49, 127.44, 55.25, 104.84]

    计算：

 (1)$  W = \frac{\sum_{i=1}^{n}x{(x_i - \overline{x})(yY_i - \overline{y})}}{\sum_{i=1}^{n}{(x_i - \overline{x})^2}}$
 
 (2)$ b = \bar{y} - w \bar{x} $

 (3) 分别输出w和b。


In [2]:
import numpy as np

# 已知列表
x = np.array([64.3, 99.6, 145.45, 63.75, 135.46, 92.85, 86.97, 144.76, 59.3, 116.03])
y = np.array([62.55, 82.42, 132.62, 73.31, 131.05, 86.57, 85.49, 127.44, 55.25, 104.84])

# (1) 计算数组x和y的均值
mean_x = np.mean(x)
mean_y = np.mean(y)

# (2) 计算w和b
w = np.sum((x - mean_x) * (y - mean_y)) / np.sum((x - mean_x) ** 2)
b = mean_y - w * mean_x

# (3) 输出w和b
print("w:", w)
print("b:", b)


w: 0.8321514698800909
b: 10.234020717002494


## 题目三（附加题）：
创建一个10×10整数二维数组，并按要求提取其中的数据。

要求：

(1) 创建10×10的二维数组a，数组元素由整数数字序列组成，从0开始递增，步长为1，输出该数组；

(2) 提取并输出二维数组a中的所有偶数行；

(3) 提取二维数组a中第2行到第8行中第3到第7列的所有数据元素，生成数组b，输出数组b及其形状。

In [1]:
import numpy as np

# (1) 创建10×10的二维数组a，数组元素由整数数字序列组成，从0开始递增，步长为1，输出该数组
a = np.arange(100).reshape(10, 10)
print("数组a:")
print(a)

# (2) 提取并输出二维数组a中的所有偶数行
even_rows = a[1::2]
print("所有偶数行:")
print(even_rows)

# (3) 提取二维数组a中第2行到第8行中第3到第7列的所有数据元素，生成数组b，输出数组b及其形状
b = a[1:8, 2:7]
print("数组b:")
print(b)
print("数组b的形状:", b.shape)


数组a:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
所有偶数行:
[[10 11 12 13 14 15 16 17 18 19]
 [30 31 32 33 34 35 36 37 38 39]
 [50 51 52 53 54 55 56 57 58 59]
 [70 71 72 73 74 75 76 77 78 79]
 [90 91 92 93 94 95 96 97 98 99]]
数组b:
[[12 13 14 15 16]
 [22 23 24 25 26]
 [32 33 34 35 36]
 [42 43 44 45 46]
 [52 53 54 55 56]
 [62 63 64 65 66]
 [72 73 74 75 76]]
数组b的形状: (7, 5)
